server:
  port: 8080

spring:
  application:
    name: monolith-app

  datasource:
    url: jdbc:mysql://172.24.238.72:3306/monolith_db?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 172.24.238.72
    port: 6379

  rabbitmq:
    host: 172.24.238.72
    port: 5672
    username: guest
    password: guest

  # 自定义配置（用于测试动态刷新）
  cloud:
    config:
      override-none: true

# 自定义配置项
app:
  greeting: "Hello from Monolith App!"
  feature:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段

logging:
  level:
    com.example.monolithapp: debug