server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.238.72:8848
        namespace: public
      config:
        server-addr: 172.24.238.72:8848
        file-extension: yml
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
    # 注意：移除本地gateway配置，完全依赖Nacos配置

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

# 日志配置
logging:
  level:
    com.example.gatewayservice: debug
    org.springframework.cloud.gateway: debug