server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://172.24.238.72:3306/user_db?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 172.24.238.72
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段

logging:
  level:
    com.example.userservice: debug