spring:
  datasource:
    url: jdbc:mysql://172.24.238.72:3306/user_db?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  config:
    app-name: "User Service"